name: .NET Linux

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore
      run: dotnet restore prometheus-net-linux.slnf
      
    - name: Build
      run: dotnet build --no-restore prometheus-net-linux.slnf
      
    - name: Test
      run: dotnet test --no-build --verbosity normal prometheus-net-linux.slnf --framework net8.0